{{ if and (eq .chezmoi.os "linux") (.chezmoi.kernel.osrelease | lower | contains "microsoft") }}
{{ $npiperelayVersion := "1.5.0" -}}
[".local/bin/npiperelay.exe"]
    type = "file"
    url = "https://github.com/albertony/npiperelay/releases/download/v{{ $npiperelayVersion }}/npiperelay_windows_amd64.exe"
    refreshPeriod = "168h"
    executable = true
    checksum.sha256 = "4752c108432382a6e77afaa3a5d9f9908e466a2cad1de4392e7f3e0775dfb1ab"
{{ end }}
