# Clone of cat(1) with syntax highlighting and Git integration
# https://formulae.brew.sh/formula/bat
brew "bat"

# Manage your dotfiles across multiple diverse machines, securely
# https://formulae.brew.sh/formula/chezmoi
brew "chezmoi"

# Modern, maintained replacement for ls
# https://formulae.brew.sh/formula/eza
brew "eza"

# Simple, fast and user-friendly alternative to find
# https://formulae.brew.sh/formula/fd
brew "fd"

# Syntax-highlighting pager for git and diff output
# https://formulae.brew.sh/formula/git-delta
brew "git-delta"

# Ping, but with a graph
# https://formulae.brew.sh/formula/gping
brew "gping"

# Modern and intuitive terminal-based text editor
# https://formulae.brew.sh/formula/micro
brew "micro"

# Search tool like grep and The Silver Searcher
# https://formulae.brew.sh/formula/ripgrep
brew "ripgrep"

# Friendly and fast tool for sending HTTP requests
# https://formulae.brew.sh/formula/xh
brew "xh"

# Shell extension to navigate your filesystem faster
# https://formulae.brew.sh/formula/zoxide
brew "zoxide"

# Cross-shell prompt for astronauts
# https://formulae.brew.sh/formula/starship
brew "starship"

# Modern shell for the GitHub era
# https://formulae.brew.sh/formula/nushell
brew "nushell"